import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';

type TelegramUpdate={message?:{message_id:number;chat:{id:number};from?:{username?:string;first_name?:string};text?:string;caption?:string;photo?:{file_id:string;file_size?:number}[];successful_payment?:{currency:string;total_amount:number}};pre_checkout_query?:{id:string};};
type Pending={chatId:number;group:number;color:string;image:string;contact:string;createdAt:string};
type Selection={group:number;color:string};
const config=()=>env as unknown as {TELEGRAM_BOT_TOKEN?:string;TELEGRAM_WEBHOOK_SECRET?:string;VOTES_CACHE:KVNamespace};
const colors:Record<string,string>={beyaz:'#ffffff',yeşil:'#13853f',yesil:'#13853f',mavi:'#1464cd',turuncu:'#f58220',sarı:'#dfb200',sari:'#dfb200',kırmızı:'#bd3643',kirmizi:'#bd3643'};
const api=async(method:string,body:Record<string,unknown>)=>{const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Telegram bot anahtarı tanımlı değil.');const response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error('Telegram isteği başarısız.');return response.json() as Promise<{result?:unknown}>};
const text=(chat_id:number,message:string)=>api('sendMessage',{chat_id,text:message});
const dataUrl=async(fileId:string)=>{const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Anahtar tanımlı değil.');const file=await api('getFile',{file_id:fileId}) as {result?:{file_path?:string}};if(!file.result?.file_path)throw Error('Görsel alınamadı.');const response=await fetch(`https://api.telegram.org/file/bot${token}/${file.result.file_path}`);const bytes=new Uint8Array(await response.arrayBuffer());if(!response.ok||bytes.length>8_000_000)throw Error('Görsel en fazla 8 MB olabilir.');let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const contentType=response.headers.get('content-type');const mediaType=contentType?.startsWith('image/')?contentType:'image/jpeg';return `data:${mediaType};base64,${btoa(binary)}`};
const details=(value='')=>{const match=value.toLocaleLowerCase('tr-TR').match(/\b([1-9]|[1-3]\d|4[01])\b\s*(beyaz|yeşil|yesil|mavi|turuncu|sarı|sari|kırmızı|kirmizi)\b/);return match?{group:Number(match[1]),color:colors[match[2]]}:null};
const pendingKey=(chatId:number)=>`telegram-pending:${chatId}`;
const selectionKey=(chatId:number)=>`telegram-selection:${chatId}`;
async function invoice(pending:Pending){const payload=`mtso-ad-${pending.chatId}-${Date.now()}`;await config().VOTES_CACHE.put(pendingKey(pending.chatId),JSON.stringify(pending),{expirationTtl:3600});await config().VOTES_CACHE.delete(selectionKey(pending.chatId));await api('sendInvoice',{chat_id:pending.chatId,title:'MTSO açılış reklamı',description:'Reklam görseliniz ödeme sonrası açılış reklam alanına yüklenir.',payload,currency:'XTR',prices:[{label:'Reklam yayın ücreti',amount:100}]});}
async function publish(chatId:number){const pending=await config().VOTES_CACHE.get<Pending>(pendingKey(chatId),'json');if(!pending)throw Error('Ödeme için bekleyen reklam görseli bulunamadı.');const type=/^data:([^;]+);base64,/.exec(pending.image)?.[1]||'image/jpeg';await config().VOTES_CACHE.put('ad-media',pending.image);await config().VOTES_CACHE.put('ad-media-meta',JSON.stringify({type,updated_at:new Date().toISOString(),source:'telegram'}));await config().VOTES_CACHE.delete(pendingKey(chatId));await text(chatId,'Ödemeniz alındı. Reklam görseliniz açılış reklam alanına yüklendi. Yönetici reklam alanını açtığında ana sayfada gösterilir.');}
export async function POST(request:Request){const c=config();if(!c.TELEGRAM_BOT_TOKEN)return Response.json({error:'Bot yapılandırılmadı.'},{status:503});if(c.TELEGRAM_WEBHOOK_SECRET&&request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==c.TELEGRAM_WEBHOOK_SECRET)return Response.json({error:'Yetkisiz.'},{status:401});try{const update=await request.json() as TelegramUpdate;if(update.pre_checkout_query){await api('answerPreCheckoutQuery',{pre_checkout_query_id:update.pre_checkout_query.id,ok:true});return Response.json({ok:true})}const message=update.message;if(!message)return Response.json({ok:true});const chatId=message.chat.id,caption=message.caption||'';if(message.successful_payment){if(message.successful_payment.currency!=='XTR'||message.successful_payment.total_amount!==100)throw Error('Geçersiz ödeme.');await publish(chatId);return Response.json({ok:true})}if(message.text==='/start'){await text(chatId,'MTSO reklam yayın botuna hoş geldiniz. Reklam görselinizi gönderin. Görsel alındıktan sonra 100 Telegram Stars ödeme bağlantısı gönderilir; ödeme tamamlanınca açılış reklam alanına yüklenir.');return Response.json({ok:true})}if(message.text){const info=details(message.text);if(info){await config().VOTES_CACHE.put(selectionKey(chatId),JSON.stringify(info),{expirationTtl:1800});await text(chatId,`Reklam görselinizi gönderin. Görsel gelince 100 Telegram Stars ödeme ekranı açılacak.`)}else await text(chatId,'Reklam görselinizi gönderin. Görsel gelince 100 Telegram Stars ödeme ekranı açılacak.');return Response.json({ok:true})}if(message.photo?.length){const info=details(caption)||await config().VOTES_CACHE.get<Selection>(selectionKey(chatId),'json');if(!info){await text(chatId,'Reklam görselinizi gönderin. Görsel gelince 100 Telegram Stars ödeme ekranı açılacak.');return Response.json({ok:true})}const photo=message.photo.at(-1);if(!photo)throw Error('Fotoğraf bulunamadı.');const pending:Pending={chatId,group:info.group,color:info.color,image:await dataUrl(photo.file_id),contact:message.from?.username?`Telegram @${message.from.username}`:(message.from?.first_name||'Telegram başvurusu'),createdAt:new Date().toISOString()};await invoice(pending);return Response.json({ok:true})}return Response.json({ok:true})}catch(error){console.error(error);return Response.json({error:'Telegram güncellemesi işlenemedi.'},{status:500})}}
export async function GET(){return Response.json({ok:true,service:'mtso-telegram-bot'})}
