import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';

type TelegramUpdate={message?:{message_id:number;chat:{id:number};from?:{username?:string;first_name?:string};text?:string;caption?:string;photo?:{file_id:string;file_size?:number}[];successful_payment?:{currency:string;total_amount:number}};pre_checkout_query?:{id:string};};
type Pending={chatId:number;group:number;color:string;image:string;contact:string;createdAt:string};
const config=()=>env as unknown as {TELEGRAM_BOT_TOKEN?:string;TELEGRAM_WEBHOOK_SECRET?:string;VOTES_CACHE:KVNamespace};
const colors:Record<string,string>={beyaz:'#ffffff',yeşil:'#13853f',yesil:'#13853f',mavi:'#1464cd',turuncu:'#f58220',sarı:'#dfb200',sari:'#dfb200',kırmızı:'#bd3643',kirmizi:'#bd3643'};
const api=async(method:string,body:Record<string,unknown>)=>{const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Telegram bot anahtarı tanımlı değil.');const response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error('Telegram isteği başarısız.');return response.json() as Promise<{result?:unknown}>};
const text=(chat_id:number,message:string)=>api('sendMessage',{chat_id,text:message});
const dataUrl=async(fileId:string)=>{const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Anahtar tanımlı değil.');const file=await api('getFile',{file_id:fileId}) as {result?:{file_path?:string}};if(!file.result?.file_path)throw Error('Görsel alınamadı.');const response=await fetch(`https://api.telegram.org/file/bot${token}/${file.result.file_path}`);const bytes=new Uint8Array(await response.arrayBuffer());if(!response.ok||bytes.length>8_000_000)throw Error('Görsel en fazla 8 MB olabilir.');let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return `data:${response.headers.get('content-type')||'image/jpeg'};base64,${btoa(binary)}`};
const details=(value='')=>{const match=value.toLocaleLowerCase('tr-TR').match(/\b([1-9]|[1-3]\d|4[01])\b\s*(beyaz|yeşil|yesil|mavi|turuncu|sarı|sari|kırmızı|kirmizi)\b/);return match?{group:Number(match[1]),color:colors[match[2]]}:null};
const pendingKey=(chatId:number)=>`telegram-pending:${chatId}`;
async function invoice(pending:Pending){const payload=`mtso-ad-${pending.chatId}-${Date.now()}`;await config().VOTES_CACHE.put(pendingKey(pending.chatId),JSON.stringify(pending),{expirationTtl:3600});await api('sendInvoice',{chat_id:pending.chatId,title:'MTSO aday afişi yayını',description:'Afişiniz ödeme sonrası ilgili meslek grubunda otomatik yayınlanır.',payload,currency:'XTR',prices:[{label:'Afiş yayın ücreti',amount:100}]});}
async function publish(chatId:number){const pending=await config().VOTES_CACHE.get<Pending>(pendingKey(chatId),'json');if(!pending)throw Error('Ödeme için bekleyen afiş bulunamadı.');await env.DB.prepare('INSERT INTO submissions(id,group_id,list_name,candidates,contact_name,image_data,status,created_at,color,submission_ip) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),pending.group,'','',pending.contact,pending.image,'approved',new Date().toISOString(),pending.color,`telegram:${chatId}`).run();await config().VOTES_CACHE.delete(pendingKey(chatId));await text(chatId,'Ödemeniz alındı. Afişiniz ilgili meslek grubunda yayınlandı.');}
export async function POST(request:Request){const c=config();if(!c.TELEGRAM_BOT_TOKEN)return Response.json({error:'Bot yapılandırılmadı.'},{status:503});if(c.TELEGRAM_WEBHOOK_SECRET&&request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==c.TELEGRAM_WEBHOOK_SECRET)return Response.json({error:'Yetkisiz.'},{status:401});try{const update=await request.json() as TelegramUpdate;if(update.pre_checkout_query){await api('answerPreCheckoutQuery',{pre_checkout_query_id:update.pre_checkout_query.id,ok:true});return Response.json({ok:true})}const message=update.message;if(!message)return Response.json({ok:true});const chatId=message.chat.id,caption=message.caption||'';if(message.successful_payment){if(message.successful_payment.currency!=='XTR'||message.successful_payment.total_amount!==100)throw Error('Geçersiz ödeme.');await publish(chatId);return Response.json({ok:true})}if(message.text==='/start'){await text(chatId,'MTSO afiş yayın botuna hoş geldiniz. Afişi tek mesajda, açıklamasına komite numarası ve liste rengini ekleyerek gönderin. Örnek: 19 mavi. Afiş alındıktan sonra 100 Telegram Stars ödeme bağlantısı gönderilir; ödeme tamamlanınca afiş otomatik yayınlanır.');return Response.json({ok:true})}if(message.photo?.length){const info=details(caption);if(!info){await text(chatId,'Afişi komite numarası ve renk açıklamasıyla tekrar gönderin. Örnek açıklama: 19 mavi');return Response.json({ok:true})}const photo=message.photo.at(-1);if(!photo)throw Error('Fotoğraf bulunamadı.');const pending:Pending={chatId,group:info.group,color:info.color,image:await dataUrl(photo.file_id),contact:message.from?.username?`Telegram @${message.from.username}`:(message.from?.first_name||'Telegram başvurusu'),createdAt:new Date().toISOString()};await invoice(pending);return Response.json({ok:true})}return Response.json({ok:true})}catch(error){console.error(error);return Response.json({error:'Telegram güncellemesi işlenemedi.'},{status:500})}}
export async function GET(){return Response.json({ok:true,service:'mtso-telegram-bot'})}
