import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';

type Photo={file_id:string;file_size?:number};
type Message={message_id:number;chat:{id:number};from?:{username?:string;first_name?:string};text?:string;photo?:Photo[];successful_payment?:{currency:string;total_amount:number}};
type Update={message?:Message;pre_checkout_query?:{id:string};callback_query?:{id:string;data?:string;from:{id:number};message?:{chat:{id:number}}}};
type Pending={chatId:number;image:string;fileId?:string;contact:string;createdAt:string;paidAt?:string;type?:string};
type Config={TELEGRAM_BOT_TOKEN?:string;TELEGRAM_WEBHOOK_SECRET?:string;ADMIN_TOKEN?:string;VOTES_CACHE:KVNamespace};
const config=()=>env as unknown as Config;
const pendingKey=(chatId:number)=>`telegram-pending:${chatId}`;
const pendingAdKey='pending-ad';
const adminChatKey='telegram-admin-chat';

async function api(method:string,body:Record<string,unknown>){const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Telegram bot anahtarı tanımlı değil.');const response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error('Telegram isteği başarısız.');return response.json() as Promise<{result?:unknown}>}
const sendText=(chatId:number,text:string,reply_markup?:unknown)=>api('sendMessage',{chat_id:chatId,text,reply_markup});
const answerCallback=(id:string,text:string)=>api('answerCallbackQuery',{callback_query_id:id,text});
async function dataUrl(fileId:string){const token=config().TELEGRAM_BOT_TOKEN;if(!token)throw Error('Anahtar tanımlı değil.');const file=await api('getFile',{file_id:fileId}) as {result?:{file_path?:string}};if(!file.result?.file_path)throw Error('Görsel alınamadı.');const response=await fetch(`https://api.telegram.org/file/bot${token}/${file.result.file_path}`);const bytes=new Uint8Array(await response.arrayBuffer());if(!response.ok||bytes.length>8_000_000)throw Error('Görsel en fazla 8 MB olabilir.');let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const contentType=response.headers.get('content-type');const mediaType=contentType?.startsWith('image/')?contentType:'image/jpeg';return `data:${mediaType};base64,${btoa(binary)}`}
async function invoice(pending:Pending){const payload=`mtso-ad-${pending.chatId}-${Date.now()}`;await config().VOTES_CACHE.put(pendingKey(pending.chatId),JSON.stringify(pending),{expirationTtl:3600});await api('sendInvoice',{chat_id:pending.chatId,title:'MTSO açılış reklamı',description:'Reklam görseliniz ödeme sonrası yönetici onayına gönderilir.',payload,currency:'XTR',prices:[{label:'Reklam yayın ücreti',amount:100}]});}
async function pendingAd(){return config().VOTES_CACHE.get<Pending>(pendingAdKey,'json')}
async function notifyAdmin(pending:Pending,chatId?:number){const saved=chatId??Number(await config().VOTES_CACHE.get(adminChatKey));if(!saved)return false;const keyboard={inline_keyboard:[[{text:'✓ Onayla ve yayınla',callback_data:'ad:approve'},{text:'✕ Reddet',callback_data:'ad:reject'}]]};const caption=`Yeni reklam onayı bekliyor\nGönderen: ${pending.contact}\nÖdeme: 100 Stars`;
 if(pending.fileId)await api('sendPhoto',{chat_id:saved,photo:pending.fileId,caption,reply_markup:keyboard});else await sendText(saved,caption,keyboard);return true;}
async function approveAd(pending:Pending){const type=/^data:([^;]+);base64,/.exec(pending.image)?.[1]||pending.type||'image/jpeg';await config().VOTES_CACHE.put('ad-media',pending.image);await config().VOTES_CACHE.put('ad-media-meta',JSON.stringify({type,updated_at:new Date().toISOString(),source:'telegram'}));await config().VOTES_CACHE.delete(pendingAdKey);}
async function handleCallback(callback:NonNullable<Update['callback_query']>){const adminChat=Number(await config().VOTES_CACHE.get(adminChatKey));if(!adminChat||callback.from.id!==adminChat){await answerCallback(callback.id,'Bu işlem için yönetici yetkisi gerekir.');return}const pending=await pendingAd();if(!pending){await answerCallback(callback.id,'Onay bekleyen reklam bulunamadı.');return}if(callback.data==='ad:approve'){await approveAd(pending);await answerCallback(callback.id,'Reklam yayınlandı.');await sendText(pending.chatId,'Reklamınız yönetici tarafından onaylandı ve açılış alanında yayınlandı.');return}if(callback.data==='ad:reject'){await config().VOTES_CACHE.delete(pendingAdKey);await answerCallback(callback.id,'Reklam reddedildi.');await sendText(pending.chatId,'Reklamınız yönetici tarafından reddedildi.');return}await answerCallback(callback.id,'Geçersiz işlem.');}

export async function POST(request:Request){const c=config();if(!c.TELEGRAM_BOT_TOKEN)return Response.json({error:'Bot yapılandırılmadı.'},{status:503});if(c.TELEGRAM_WEBHOOK_SECRET&&request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==c.TELEGRAM_WEBHOOK_SECRET)return Response.json({error:'Yetkisiz.'},{status:401});try{const update=await request.json() as Update;if(update.pre_checkout_query){await api('answerPreCheckoutQuery',{pre_checkout_query_id:update.pre_checkout_query.id,ok:true});return Response.json({ok:true})}if(update.callback_query){await handleCallback(update.callback_query);return Response.json({ok:true})}const message=update.message;if(!message)return Response.json({ok:true});const chatId=message.chat.id;
 if(message.successful_payment){if(message.successful_payment.currency!=='XTR'||message.successful_payment.total_amount!==100)throw Error('Geçersiz ödeme.');const pending=await config().VOTES_CACHE.get<Pending>(pendingKey(chatId),'json');if(!pending)throw Error('Ödeme için bekleyen reklam görseli bulunamadı.');const type=/^data:([^;]+);base64,/.exec(pending.image)?.[1]||'image/jpeg';const review={...pending,type,paidAt:new Date().toISOString()};await config().VOTES_CACHE.put(pendingAdKey,JSON.stringify(review));await config().VOTES_CACHE.delete(pendingKey(chatId));const sent=await notifyAdmin(review);await sendText(chatId,sent?'Ödemeniz alındı. Reklam görseliniz yönetici onayına gönderildi.':'Ödemeniz alındı. Reklam görseliniz yönetici onay kuyruğunda.');return Response.json({ok:true})}
 const command=(message.text||'').trim();if(command==='/start'){await sendText(chatId,'MTSO reklam yayın botuna hoş geldiniz. Reklam görselini gönderin; ardından 100 Telegram Stars ödeme ekranı açılır. Ödeme sonrası yönetici onayıyla açılış reklamında yayınlanır. Yönetici yetkilendirmesi için /yonetici kod yazın.');return Response.json({ok:true})}
 if(command.startsWith('/yonetici ')){const code=command.slice('/yonetici '.length).trim();if(!c.ADMIN_TOKEN||code!==c.ADMIN_TOKEN){await sendText(chatId,'Yönetici kodu hatalı.');return Response.json({ok:true})}await config().VOTES_CACHE.put(adminChatKey,String(chatId));await sendText(chatId,'Bu Telegram hesabı reklam yöneticisi olarak yetkilendirildi. Yeni ödemeler için Onayla / Reddet düğmeleri buraya gelir.');const waiting=await pendingAd();if(waiting)await notifyAdmin(waiting,chatId);return Response.json({ok:true})}
 if(command==='/bekleyen'){const adminChat=Number(await config().VOTES_CACHE.get(adminChatKey));if(adminChat!==chatId){await sendText(chatId,'Bu komut yalnızca yetkili yönetici içindir.');return Response.json({ok:true})}const waiting=await pendingAd();if(waiting)await notifyAdmin(waiting,chatId);else await sendText(chatId,'Onay bekleyen reklam yok.');return Response.json({ok:true})}
 if(message.photo?.length){const photo=message.photo.at(-1);if(!photo)throw Error('Fotoğraf bulunamadı.');const pending:Pending={chatId,image:await dataUrl(photo.file_id),fileId:photo.file_id,contact:message.from?.username?`Telegram @${message.from.username}`:(message.from?.first_name||'Telegram başvurusu'),createdAt:new Date().toISOString()};await invoice(pending);return Response.json({ok:true})}
 if(command)await sendText(chatId,'Reklam görselinizi gönderin. Görsel gelince 100 Telegram Stars ödeme ekranı açılacak.');return Response.json({ok:true})}catch(error){console.error(error);return Response.json({error:'Telegram güncellemesi işlenemedi.'},{status:500})}}
export async function GET(){return Response.json({ok:true,service:'mtso-telegram-bot'})}
